### ISSUE TITLE
Plans to continue dev.?

### ISSUE THREAD

**Issue by rolfea** [duffleit/vscode-specflow#1]
Hi there,  
  
This plugin would be pretty useful, and I was wondering if there were any plans to continue dev. on it. Any help needed?

**Comment by mariomerco** [comment]
@rolfea awesome question!!!! I'd like to help as well if there are plans to continue developing this.

**Comment by duffleit** [comment]
Hi, I currently have no plans to pursue the project further, since I focused on other stuff. But of course, feel free to fork :) 
Probably @techtalk or @SabotageAndi can tell you if there are any efforts to build a Specflow integration for VSCode. 

BR, David
